### ISSUE TITLE
Make new line optionnal

### ISSUE THREAD

**Issue by feugy** [beansandcurry/jQuery-Textarea-Auto-Resize-Plugin#1]
Hi, and thank you for your work.
This is an enhancement proposal: in my case, I do not want to have empty new line bellow my text.

I proposed you a new option: `withNewline` (default to true) which allow to disable it: 

line 14:

``` javascript
   var settings = $.extend({
        debug: false,
        withNewline: true,
      }, options),
```

line32:

``` javascript
    /* Replaces line breaks with <br /> tags for the text entered in the textarea */
    function textarea2div(text) {
      var breakTag = '<br />';
      return (text + (settings.withNewline ? '<br />~' : '')).replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1' + breakTag + '$2');
    }
```

And It would be nice to add a version number :)

Thanks for all

**Comment by tanerdiler** [comment]
This option must be placed in new version.
